config/routes.rb
Rails.application.routes.draw do
  resources :reward2s
  resources :clones
  resources :rewards
  root 'index#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clone.rb
class Clone < ApplicationRecord
end

app/models/reward.rb
class Reward < ApplicationRecord
end

app/models/reward2.rb
class Reward2 < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clones_controller.rb
class ClonesController < ApplicationController
  before_action :set_clone, only: %i[ show edit update destroy ]

  # GET /clones or /clones.json
  def index
    @clones = Clone.all
  end

  # GET /clones/1 or /clones/1.json
  def show
  end

  # GET /clones/new
  def new
    @clone = Clone.new
  end

  # GET /clones/1/edit
  def edit
  end

  # POST /clones or /clones.json
  def create
    @clone = Clone.new(clone_params)

    respond_to do |format|
      if @clone.save
        format.html { redirect_to clone_url(@clone), notice: "Clone was successfully created." }
        format.json { render :show, status: :created, location: @clone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clones/1 or /clones/1.json
  def update
    respond_to do |format|
      if @clone.update(clone_params)
        format.html { redirect_to clone_url(@clone), notice: "Clone was successfully updated." }
        format.json { render :show, status: :ok, location: @clone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clones/1 or /clones/1.json
  def destroy
    @clone.destroy

    respond_to do |format|
      format.html { redirect_to clones_url, notice: "Clone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clone
      @clone = Clone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clone_params
      params.require(:clone).permit(:name, :DOB)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end
end

app/controllers/reward2s_controller.rb
class Reward2sController < ApplicationController
  before_action :set_reward2, only: %i[ show edit update destroy ]

  # GET /reward2s or /reward2s.json
  def index
    @reward2s = Reward2.all
  end

  # GET /reward2s/1 or /reward2s/1.json
  def show
  end

  # GET /reward2s/new
  def new
    @reward2 = Reward2.new
  end

  # GET /reward2s/1/edit
  def edit
  end

  # POST /reward2s or /reward2s.json
  def create
    @reward2 = Reward2.new(reward2_params)

    respond_to do |format|
      if @reward2.save
        format.html { redirect_to reward2_url(@reward2), notice: "Reward2 was successfully created." }
        format.json { render :show, status: :created, location: @reward2 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reward2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reward2s/1 or /reward2s/1.json
  def update
    respond_to do |format|
      if @reward2.update(reward2_params)
        format.html { redirect_to reward2_url(@reward2), notice: "Reward2 was successfully updated." }
        format.json { render :show, status: :ok, location: @reward2 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reward2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reward2s/1 or /reward2s/1.json
  def destroy
    @reward2.destroy

    respond_to do |format|
      format.html { redirect_to reward2s_url, notice: "Reward2 was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward2
      @reward2 = Reward2.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reward2_params
      params.require(:reward2).permit(:reward, :price, :value, :status)
    end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: %i[ show edit update destroy ]

  # GET /rewards or /rewards.json
  def index
    @rewards = Reward.all
  end

  # GET /rewards/1 or /rewards/1.json
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards or /rewards.json
  def create
    @reward = Reward.new(reward_params)

    respond_to do |format|
      if @reward.save
        format.html { redirect_to reward_url(@reward), notice: "Reward was successfully created." }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1 or /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to reward_url(@reward), notice: "Reward was successfully updated." }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1 or /rewards/1.json
  def destroy
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url, notice: "Reward was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reward_params
      params.require(:reward).permit(:reward, :price, :value, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clones_helper.rb
module ClonesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/reward2s_helper.rb
module Reward2sHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/clones/_form.html.erb
<%= form_with(model: clone) do |form| %>
  <% if clone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clone.errors.count, "error") %> prohibited this clone from being saved:</h2>

      <ul>
        <% clone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :DOB %>
    <%= form.date_select :DOB %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clones/edit.html.erb
<h1>Editing Clone</h1>

<%= render 'form', clone: @clone %>

<%= link_to 'Show', @clone %> |
<%= link_to 'Back', clones_path %>

app/views/clones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clones.each do |clone| %>
      <tr>
        <td><%= clone.name %></td>
        <td><%= clone.DOB %></td>
        <td><%= link_to 'Show', clone %></td>
        <td><%= link_to 'Edit', edit_clone_path(clone) %></td>
        <td><%= link_to 'Destroy', clone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clone', new_clone_path %>

app/views/clones/new.html.erb
<h1>New Clone</h1>

<%= render 'form', clone: @clone %>

<%= link_to 'Back', clones_path %>

app/views/clones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @clone.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @clone.DOB %>
</p>

<%= link_to 'Edit', edit_clone_path(@clone) %> |
<%= link_to 'Back', clones_path %>

app/views/index/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/index/home.html.erb
<h1>Index#home</h1>
<p>Find me in app/views/index/home.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reward</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "index/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/reward2s/_form.html.erb
<%= form_with(model: reward2) do |form| %>
  <% if reward2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward2.errors.count, "error") %> prohibited this reward2 from being saved:</h2>

      <ul>
        <% reward2.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reward %>
    <%= form.text_area :reward %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reward2s/edit.html.erb
<h1>Editing Reward2</h1>

<%= render 'form', reward2: @reward2 %>

<%= link_to 'Show', @reward2 %> |
<%= link_to 'Back', reward2s_path %>

app/views/reward2s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reward2s</h1>

<table>
  <thead>
    <tr>
      <th>Reward</th>
      <th>Price</th>
      <th>Value</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reward2s.each do |reward2| %>
      <tr>
        <td><%= reward2.reward %></td>
        <td><%= reward2.price %></td>
        <td><%= reward2.value %></td>
        <td><%= reward2.status %></td>
        <td><%= link_to 'Show', reward2 %></td>
        <td><%= link_to 'Edit', edit_reward2_path(reward2) %></td>
        <td><%= link_to 'Destroy', reward2, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward2', new_reward2_path %>

app/views/reward2s/new.html.erb
<h1>New Reward2</h1>

<%= render 'form', reward2: @reward2 %>

<%= link_to 'Back', reward2s_path %>

app/views/reward2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reward:</strong>
  <%= @reward2.reward %>
</p>

<p>
  <strong>Price:</strong>
  <%= @reward2.price %>
</p>

<p>
  <strong>Value:</strong>
  <%= @reward2.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @reward2.status %>
</p>

<%= link_to 'Edit', edit_reward2_path(@reward2) %> |
<%= link_to 'Back', reward2s_path %>

app/views/rewards/_form.html.erb
<%= form_with(model: reward) do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% reward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reward %>
    <%= form.text_area :reward %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rewards</h1>

<table>
  <thead>
    <tr>
      <th>Reward</th>
      <th>Price</th>
      <th>Value</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= reward.reward %></td>
        <td><%= reward.price %></td>
        <td><%= reward.value %></td>
        <td><%= reward.status %></td>
        <td><%= link_to 'Show', reward %></td>
        <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
        <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reward:</strong>
  <%= @reward.reward %>
</p>

<p>
  <strong>Price:</strong>
  <%= @reward.price %>
</p>

<p>
  <strong>Value:</strong>
  <%= @reward.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @reward.status %>
</p>

<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>